import type { LogisticsPermissionCode as BackendPermissionCode } from './generated/permission-codes'

/**
 * Nombres simbólicos para los códigos del catálogo del backend.
 *
 * El `satisfies` del final es la parte importante: ata cada valor al contrato generado
 * desde `rbac/permission_catalog.py`, de modo que un código que el backend no conozca
 * deja de compilar. Antes esta lista se mantenía a mano y derivó hasta tener 131 códigos
 * inexistentes —23 de ellos exigidos por pantallas vivas— sin que nada avisara: eran
 * gates que no podían abrirse nunca.
 *
 * Para añadir un permiso: primero al catálogo del backend, luego regenerar el contrato
 * (`npm run permissions:contract`) y por último darle nombre aquí.
 */
export const LOGISTICS_PERMISSIONS = {
  organizations: {
    read: 'logistics.organizations.read',
    create: 'logistics.organizations.create',
    update: 'logistics.organizations.update',
    changeStatus: 'logistics.organizations.change_status',
  },
  branches: {
    read: 'logistics.branches.read',
    create: 'logistics.branches.create',
    update: 'logistics.branches.update',
    changeStatus: 'logistics.branches.change_status',
  },
  warehouses: {
    read: 'logistics.warehouses.read',
    create: 'logistics.warehouses.create',
    update: 'logistics.warehouses.update',
    changeStatus: 'logistics.warehouses.change_status',
    setDefault: 'logistics.warehouses.set_default',
    manage: 'logistics.warehouses.manage',
  },
  roles: {
    read: 'logistics.roles.read',
  },
  roleAssignments: {
    read: 'logistics.role_assignments.read',
    create: 'logistics.role_assignments.create',
    update: 'logistics.role_assignments.update',
    revoke: 'logistics.role_assignments.revoke',
  },
  rolePermissions: {
    read: 'logistics.role_permissions.read',
    update: 'logistics.role_permissions.update',
  },
  permissions: {
    read: 'logistics.permissions.read',
  },
  documents: {
    read: 'logistics.documents.read',
    preview: 'logistics.documents.preview',
    download: 'logistics.documents.download',
    export: 'logistics.documents.export',
    cancel: 'logistics.documents.cancel',
    reprint: 'logistics.documents.reprint',
  },
  audit: {
    read: 'logistics.audit.read',
    export: 'logistics.audit.export',
    readSensitive: 'logistics.audit.read_sensitive',
  },
  receptionAppointments: {
    preview: 'logistics.reception_appointments.preview',
    download: 'logistics.reception_appointments.download',
  },
  companySettings: {
    read: 'logistics.company_profile.read',
    create: 'logistics.company_profile.create',
    update: 'logistics.company_profile.update',
    activate: 'logistics.company_profile.activate',
    readHistory: 'logistics.company_profile.read_history',
  },
  catalog: {
    read: 'logistics.products.read',
    create: 'logistics.products.create',
    update: 'logistics.products.update',
    activate: 'logistics.products.activate',
  },
  units: {
    read: 'logistics.units.read',
    create: 'logistics.units.create',
    update: 'logistics.units.update',
    manage: 'logistics.unit_conversions.create',
    evaluate: 'logistics.unit_conversions.evaluate',
  },
  partners: {
    read: 'logistics.business_partners.read',
    create: 'logistics.business_partners.create',
    manage: 'logistics.business_partners.create',
    activate: 'logistics.business_partners.activate',
    block: 'logistics.business_partners.block',
  },
  purchaseOrders: {
    read: 'logistics.purchase_orders.read',
    create: 'logistics.purchase_orders.create',
    update: 'logistics.purchase_orders.update',
    manage: 'logistics.purchase_orders.create',
    approve: 'logistics.purchase_orders.approve',
    issue: 'logistics.purchase_orders.issue',
    cancel: 'logistics.purchase_orders.cancel',
  },
  purchaseOrdersV2: {
    view: 'logistics.purchase_orders.read',
    generate: 'logistics.purchase_orders.create',
    update: 'logistics.purchase_orders.update',
    submitForApproval: 'logistics.purchase_orders.update',
    approveTransitional: 'logistics.purchase_orders.approve',
    reject: 'logistics.purchase_orders.approve',
    return: 'logistics.purchase_orders.approve',
    issue: 'logistics.purchase_orders.issue',
    cancel: 'logistics.purchase_orders.cancel',
  },
  procurementApprovals: {
    view: 'logistics.procurement_approvals.read',
    decide: 'logistics.procurement_approvals.decide',
    policiesRead: 'logistics.procurement_approval_policies.read',
    policiesCreate: 'logistics.procurement_approval_policies.create',
    policiesUpdate: 'logistics.procurement_approval_policies.update',
    policiesActivate: 'logistics.procurement_approval_policies.activate',
  },
  rucIntegration: {
    read: 'logistics.ruc_lookup.read',
    lookup: 'logistics.ruc_lookup.read',
    lookupEnriched: 'logistics.ruc_lookup.read',
    manageAssisted: 'logistics.ruc_verifications.create',
    approveAssisted: 'logistics.ruc_verifications.approve',
    manageDatasets: 'logistics.ruc_datasets.read',
    import: 'logistics.ruc_imports.execute',
    activate: 'logistics.ruc_datasets.activate',
    rollback: 'logistics.ruc_datasets.rollback',
  },
  vehicles: {
    read: 'logistics.vehicles.read',
    create: 'logistics.vehicles.create',
    update: 'logistics.vehicles.update',
    manage: 'logistics.vehicles.create',
    activate: 'logistics.vehicles.activate',
    changePlate: 'logistics.vehicle_plates.change',
    manageOwnership: 'logistics.vehicle_ownership.manage',
    manageCarrier: 'logistics.vehicle_carrier_assignments.manage',
    manageDocuments: 'logistics.vehicle_documents.create',
    block: 'logistics.vehicles.block',
    verify: 'logistics.vehicles.verify',
  },
  purchaseRequisitions: {
    read: 'logistics.purchase_requisitions.read',
    create: 'logistics.purchase_requisitions.create',
    update: 'logistics.purchase_requisitions.edit',
    submit: 'logistics.purchase_requisitions.submit',
    review: 'logistics.purchase_requisitions.review',
    approve: 'logistics.purchase_requisitions.approve',
    reject: 'logistics.purchase_requisitions.approve',
    return: 'logistics.purchase_requisitions.approve',
    withdraw: 'logistics.purchase_requisitions.submit',
    cancel: 'logistics.purchase_requisitions.cancel',
  },
  costCenters: {
    read: 'logistics.cost_centers.read',
    manage: 'logistics.cost_centers.manage',
  },
  vehicleVerifications: {
    read: 'logistics.vehicles.verify',
    request: 'logistics.vehicles.verify',
    retry: 'logistics.vehicles.verify',
    revoke: 'logistics.vehicles.verify',
    viewSensitiveResult: 'logistics.vehicles.verify',
    createAssisted: 'logistics.vehicles.verify',
    approveAssisted: 'logistics.vehicles.verify',
    applyResult: 'logistics.vehicles.verify',
    resolveConflict: 'logistics.vehicles.verify',
    viewEvidence: 'logistics.vehicles.verify',
    manageEvidence: 'logistics.vehicles.verify',
    viewSources: 'logistics.vehicles.verify',
    manageSources: 'logistics.vehicles.verify',
    viewRequirements: 'logistics.vehicles.verify',
    manageRequirements: 'logistics.vehicles.verify',
    activateRequirements: 'logistics.vehicles.verify',
    viewReviewTasks: 'logistics.vehicles.verify',
  },
  drivers: {
    read: 'logistics.drivers.read',
    create: 'logistics.drivers.create',
    update: 'logistics.drivers.update',
    manage: 'logistics.drivers.create',
    manageCategories: 'logistics.drivers.update',
  },
  supplierEvaluations: {
    templatesRead: 'logistics.supplier_evaluation_templates.read',
    create: 'logistics.quotation_evaluations.create',
    calculate: 'logistics.quotation_evaluations.calculate',
    recordDecision: 'logistics.quotation_evaluation_decisions.record',
    manageTemplates: 'logistics.supplier_evaluation_templates.manage',
  },
  gateControl: {
    view: 'logistics.gate_check_ins.read',
    resolveAppointment: 'logistics.gate_check_ins.read',
    createCheckIn: 'logistics.gate_check_ins.create',
    createWalkIn: 'logistics.gate_check_ins.walk_in',
    recordArrival: 'logistics.gate_check_ins.create',
    startVerification: 'logistics.gate_check_ins.start_verification',
    manageVehicleInspection: 'logistics.gate_vehicle_inspections.manage',
    manageDriverInspection: 'logistics.gate_driver_inspections.manage',
    manageDocuments: 'logistics.gate_document_inspections.manage',
    manageSeal: 'logistics.gate_seal_inspections.manage',
    capturePhoto: 'logistics.gate_photo_evidence.capture',
    viewSensitivePhoto: 'logistics.gate_sensitive_evidence.read',
    manageChecks: 'logistics.gate_document_inspections.manage',
    requestException: 'logistics.gate_exceptions.request',
    approveException: 'logistics.gate_exceptions.approve',
    hold: 'logistics.gate_check_ins.hold',
    requestSupervisor: 'logistics.gate_entry.supervise',
    authorize: 'logistics.gate_entry.authorize',
    authorizeWithObservations: 'logistics.gate_entry.authorize_with_observations',
    deny: 'logistics.gate_entry.deny',
    complete: 'logistics.gate_check_ins.complete',
    previewCPV: 'logistics.gate_documents.preview',
    issueCPV: 'logistics.gate_documents.issue',
    downloadCPV: 'logistics.gate_documents.download',
    requestCorrection: 'logistics.gate_check_ins.request_correction',
    viewHistory: 'logistics.gate_check_ins.read_history',
    viewIntegrity: 'logistics.gate_check_ins.read_history',
    viewDockPreparation: 'logistics.gate_check_ins.read',
    manageGates: 'logistics.warehouse_gates.manage',
    managePolicies: 'logistics.gate_check_ins.start_verification',
  },
  inboundDocks: {
    view: 'logistics.inbound_dock_queue.read',
    manageDocks: 'logistics.warehouse_docks.manage',
    manageBlackouts: 'logistics.warehouse_docks.manage_blackouts',
    viewQueue: 'logistics.inbound_dock_queue.read',
    changePriority: 'logistics.inbound_dock_queue.change_priority',
    planAssignment: 'logistics.inbound_dock_assignments.plan',
    assign: 'logistics.inbound_dock_assignments.assign',
    reassign: 'logistics.inbound_dock_assignments.reassign',
    startMovement: 'logistics.inbound_dock_assignments.assign',
    confirmArrival: 'logistics.inbound_dock_assignments.assign',
    manageReadiness: 'logistics.unloading_operations.manage_readiness',
    manageResponsibles: 'logistics.unloading_operations.manage_responsibles',
    recordSealOpening: 'logistics.unloading_operations.record_seal_opening',
    startUnloading: 'logistics.unloading_operations.start',
    pause: 'logistics.unloading_operations.pause',
    resume: 'logistics.unloading_operations.resume',
    abort: 'logistics.unloading_operations.abort',
    complete: 'logistics.unloading_operations.complete',
    releaseDock: 'logistics.inbound_dock_assignments.release',
    requestTimeCorrection: 'logistics.unloading_operations.correct_times',
    approveTimeCorrection: 'logistics.unloading_operations.correct_times',
    viewMetrics: 'logistics.dock_operational_metrics.read',
    export: 'logistics.dock_operational_metrics.export',
    viewHistory: 'logistics.dock_operational_integrity.read',
    viewReceivingPreparation: 'logistics.unloading_operations.read',
  },
  inboundReceiving: {
  },
  receptionDifferences: {
    view: 'logistics.reception_difference_cases.read',
    create: 'logistics.reception_difference_cases.create',
    update: 'logistics.reception_difference_cases.update',
    formalizeCandidates: 'logistics.reception_difference_cases.create',
    createManualItem: 'logistics.reception_difference_items.create',
    uploadEvidence: 'logistics.reception_difference_evidence.create',
    viewSensitiveEvidence: 'logistics.reception_difference_evidence.read',
    proposeResponsibility: 'logistics.reception_difference_responsibility.create',
    reviewResponsibility: 'logistics.reception_difference_responsibility.review',
    acknowledgeResponsibility: 'logistics.reception_difference_responsibility.acknowledge',
    disputeResponsibility: 'logistics.reception_difference_responsibility.dispute',
    submit: 'logistics.reception_difference_cases.submit',
    review: 'logistics.reception_difference_cases.review',
    requestChanges: 'logistics.reception_difference_cases.review',
    markReadyForApproval: 'logistics.reception_difference_cases.review',
    approve: 'logistics.reception_difference_cases.approve',
    previewDIF: 'logistics.reception_difference_documents.read',
    issueDIF: 'logistics.reception_difference_documents.issue',
    downloadDIF: 'logistics.reception_difference_documents.read',
    reprintDIF: 'logistics.reception_difference_documents.read',
    cancelDIF: 'logistics.reception_difference_documents.cancel',
    downloadPackage: 'logistics.reception_difference_documents.package',
    close: 'logistics.reception_difference_cases.close',
    viewHistory: 'logistics.reception_difference_cases.read',
    viewIntegrity: 'logistics.reception_difference_cases.read',
    viewQualityPreparation: 'logistics.reception_difference_cases.read',
    viewQuarantineRecommendations: 'logistics.reception_difference_cases.read',
    viewClaimPreparation: 'logistics.reception_difference_cases.read',
  },
  files: {
    read: 'logistics.files.read',
    upload: 'logistics.files.upload',
    download: 'logistics.files.download',
    archive: 'logistics.files.archive',
    restore: 'logistics.files.restore',
  },
  qualityInspectionPlans: {
    read: 'logistics.quality_plan.read',
    create: 'logistics.quality_plan.create',
    update: 'logistics.quality_plan.update',
    archive: 'logistics.quality_plan.archive',
    restore: 'logistics.quality_plan.update',
    createVersion: 'logistics.quality_plan.create_version',
    cloneVersion: 'logistics.quality_plan.create_version',
    manageScopes: 'logistics.quality_plan.create_scope',
    manageControls: 'logistics.quality_plan.create_control',
    manageTolerances: 'logistics.quality_plan.create_tolerance',
    manageSampling: 'logistics.quality_plan.create_sampling',
    manageCertificates: 'logistics.quality_plan.create_certificate',
    validate: 'logistics.quality_plan.read',
    detectConflicts: 'logistics.quality_plan.read',
    activate: 'logistics.quality_plan.activate',
    retire: 'logistics.quality_plan.retire_version',
    preview: 'logistics.quality_plan.read',
    resolve: 'logistics.quality_plan.read',
    viewHistory: 'logistics.quality_plan.read_history',
    viewIntegrity: 'logistics.quality_plan.read_integrity',
    viewFutureTemplate: 'logistics.quality_plan.read',
  },
  qualityTolerances: {
    read: 'logistics.quality_plan.read',
    create: 'logistics.quality_plan.create_tolerance',
  },
  qualitySamplingPlans: {
    read: 'logistics.quality_plan.read',
    create: 'logistics.quality_plan.create_sampling',
  },
  qualityCertificateRequirements: {
  },
  quarantine: {
    view: 'logistics.quality_quarantine.read',
    createQuarantine: 'logistics.quality_quarantine.create',
    activateQuarantine: 'logistics.quality_quarantine.activate',
    manageZones: 'logistics.quality_quarantine.manage_zones',
    confirmPlacement: 'logistics.quality_quarantine.confirm_placement',
    materializeInspection: 'logistics.quality_inspections.create',
    startInspection: 'logistics.quality_inspections.start',
    pauseInspection: 'logistics.quality_inspections.pause',
    resumeInspection: 'logistics.quality_inspections.resume',
    recordControlResult: 'logistics.quality_inspections.record_results',
    recordMeasurement: 'logistics.quality_inspections.record_measurements',
    recordSample: 'logistics.quality_inspections.record_samples',
    reviewCertificate: 'logistics.quality_inspections.review_certificates',
    uploadEvidence: 'logistics.quality_inspections.upload_evidence',
    validateInspection: 'logistics.quality_inspections.validate',
    completeInspection: 'logistics.quality_inspections.complete',
    correctControl: 'logistics.quality_inspections.record_results',
    proposeDecision: 'logistics.quality_disposition.propose',
    approveQuality: 'logistics.quality_disposition.approve',
    keepQuarantined: 'logistics.quality_disposition.keep_quarantined',
    requestReinspection: 'logistics.quality_inspections.request_reinspection',
    requestRelease: 'logistics.quality_quarantine.request_release',
    approveRelease: 'logistics.quality_quarantine.approve_release',
    executeRelease: 'logistics.quality_quarantine.execute_release',
    directRelease: 'logistics.quality_quarantine.direct_release',
    requestRejection: 'logistics.quality_quarantine.request_rejection',
    approveRejection: 'logistics.quality_quarantine.approve_rejection',
    executeRejection: 'logistics.quality_quarantine.execute_rejection',
    splitAllocation: 'logistics.inbound_inventory_disposition.split',
    previewNC: 'logistics.quality_nonconformities.preview',
    issueNC: 'logistics.quality_nonconformities.issue',
    downloadNC: 'logistics.quality_nonconformities.download',
    cancelNC: 'logistics.quality_nonconformities.cancel',
    viewHistory: 'logistics.quality_quarantine.read_history',
    viewIntegrity: 'logistics.quality_quarantine.read_integrity',
    viewPutawayPreparation: 'logistics.quality_future_preparation.read',
    viewFuturePreparations: 'logistics.quality_future_preparation.read',
  },
  putaway: {
    view: 'logistics.putaway.read',
    viewOrders: 'logistics.putaway.read',
    createOrder: 'logistics.putaway.create',
    updateOrder: 'logistics.putaway.update',
    cancelOrder: 'logistics.putaway.update',
    planOrder: 'logistics.putaway.update',
    holdOrder: 'logistics.putaway.update',
    resumeOrder: 'logistics.putaway.update',
    viewTasks: 'logistics.putaway.read',
    assignTask: 'logistics.putaway.assign',
    startTask: 'logistics.putaway.execute',
    completeTask: 'logistics.putaway.execute',
    divertTask: 'logistics.putaway.override',
    cancelTask: 'logistics.putaway.execute',
    bulkAssign: 'logistics.putaway.assign',
    bulkComplete: 'logistics.putaway.execute',
    viewCandidates: 'logistics.putaway.read',
    recomputeCandidates: 'logistics.putaway.execute',
    viewCapacity: 'logistics.putaway.policies.read',
    viewCompatibility: 'logistics.putaway.policies.read',
    viewRotation: 'logistics.putaway.policies.read',
    viewProximity: 'logistics.putaway.policies.read',
    viewExceptions: 'logistics.putaway.read',
    acknowledgeException: 'logistics.putaway.execute',
    resolveException: 'logistics.putaway.execute',
    escalateException: 'logistics.putaway.override',
    assignException: 'logistics.putaway.assign',
    generateDocument: 'logistics.putaway.read',
    downloadDocument: 'logistics.putaway.read',
    viewHistory: 'logistics.putaway.read',
    viewIntegrity: 'logistics.putaway.read',
    mobileAccess: 'logistics.putaway.execute',
    mobileScan: 'logistics.putaway.execute',
    confirmPlacement: 'logistics.putaway.execute',
  },
  inventoryLedger: {
    view: 'logistics.inventory_ledger.read',
    validatePreparedEvent: 'logistics.inventory_ledger.validate_prepared_event',
    postPreparedEvent: 'logistics.inventory_ledger.post_prepared_event',
    retryFailedPosting: 'logistics.inventory_ledger.retry_failed_posting',
    requestCompensation: 'logistics.inventory_ledger.request_compensation',
    reviewCompensation: 'logistics.inventory_ledger.review_compensation',
    approveCompensation: 'logistics.inventory_ledger.approve_compensation',
    executeCompensation: 'logistics.inventory_ledger.execute_compensation',
    export: 'logistics.inventory_kardex.export',
    verifyPartition: 'logistics.inventory_ledger.verify',
    createCheckpoint: 'logistics.inventory_ledger.create_checkpoint',
    reconcile: 'logistics.inventory_ledger.reconcile',
    viewBalancePreparation: 'logistics.inventory_ledger.read_balance_preparation',
    viewTraceabilityPreparation: 'logistics.inventory_ledger.read_traceability_preparation',
  },
  // Fase 045 · Saldos de inventario.
  // `read`, `rebuild` y `rebuildViaLedger` son los códigos que exige el router
  // real del backend (inventory/balances/.../router.py, commit 337007b).
  inventoryBalances: {
    read: 'logistics.inventory.read',
    rebuild: 'logistics.inventory.rebuild',
    rebuildViaLedger: 'logistics.inventory_ledger.reconcile',
    view: 'logistics.inventory_ledger.read',
    viewPositions: 'logistics.inventory_ledger.read',
    viewMovements: 'logistics.inventory_ledger.read',
    viewFormulas: 'logistics.inventory_ledger.read',
    viewFreshness: 'logistics.inventory_ledger.read',
    viewHistorical: 'logistics.inventory_ledger.read',
    reconcile: 'logistics.inventory_ledger.reconcile',
    reviewReconciliation: 'logistics.inventory_ledger.reconcile',
    createCheckpoint: 'logistics.inventory_ledger.create_checkpoint',
    export: 'logistics.inventory_kardex.export',
    validateAvailability: 'logistics.inventory_ledger.read',
  },
} as const satisfies Record<string, Record<string, BackendPermissionCode>>

export type LogisticsPermissionCode =
  | (typeof LOGISTICS_PERMISSIONS)[keyof typeof LOGISTICS_PERMISSIONS][keyof (typeof LOGISTICS_PERMISSIONS)[keyof typeof LOGISTICS_PERMISSIONS]]

export type LogisticsPermissionPath = keyof typeof LOGISTICS_PERMISSIONS

export type LogisticsPermissionActionGroup<T extends LogisticsPermissionPath> =
  (typeof LOGISTICS_PERMISSIONS)[T]

